<template>
	<iframe
		src="https://ghbtns.com/github-btn.html?user=kevsersrca&repo=blog&type=star&count=true&size=large"
		frameborder="0"
		scrolling="0"
		width="130px"
		height="30px"
	></iframe>
</template>
